# Experiment with tst_param and average_grad 

## What are `tst_param` and `average_grad`

In [1]:
# CLICK ME
from fastai.vision.all import *
from IPython.display import IFrame
from pdb import set_trace

In [6]:
import pdb

In [ ]:
!python

Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:28:27) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

In [6]:
def average_grad(p, mom, dampening=False, grad_avg=None, **kwargs):
    "Keeps track of the avg grads of `p` in `state` with `mom`."
    if grad_avg is None: grad_avg = torch.zeros_like(p.grad.data)
    damp = 1-mom if dampening else 1.
    grad_avg.mul_(mom).add_(p.grad.data, alpha=damp)
    return {'grad_avg': grad_avg}

average_grad.defaults = dict(mom=0.9)

`dampening=False` gives the classical formula for momentum in SGD: 
```
new_val = old_val * mom + grad
```
whereas `dampening=True` makes it an exponential moving average:
```
new_val = old_val * mom + grad * (1-mom)
```

In [7]:
def tst_param(val, grad=None):
    "Create a tensor with `val` and a gradient of `grad` for testing"
    res = tensor([val]).float()
    res.grad = tensor([val/10 if grad is None else grad]).float()
    return res

In [8]:
p = tst_param([1,2,3], [4,5,6]) 

state = {}
state = average_grad(p, mom=0.9, **state)
test_eq(state['grad_avg'], p.grad)
print(state)

state = average_grad(p, mom=0.9, **state)
test_eq(state['grad_avg'], p.grad * 1.9)
print(state)

#Test dampening
state = {}
state = average_grad(p,  mom=0.9, dampening=True, **state)
test_eq(state['grad_avg'], 0.1*p.grad)
print(state)

state = average_grad(p, mom=0.9, dampening=True, **state)
test_close(state['grad_avg'], (0.1*0.9+0.1)*p.grad)
print(state)

{'grad_avg': tensor([[4., 5., 6.]])}
{'grad_avg': tensor([[ 7.6000,  9.5000, 11.4000]])}
{'grad_avg': tensor([[0.4000, 0.5000, 0.6000]])}
{'grad_avg': tensor([[0.7600, 0.9500, 1.1400]])}


## Experiment tst_param with pdb

In [2]:
def average_grad(p, mom, dampening=False, grad_avg=None, **kwargs):
    "Keeps track of the avg grads of `p` in `state` with `mom`."
    set_trace()
    if grad_avg is None: grad_avg = torch.zeros_like(p.grad.data)
    damp = 1-mom if dampening else 1.
    grad_avg.mul_(mom).add_(p.grad.data, alpha=damp)
    return {'grad_avg': grad_avg}

average_grad.defaults = dict(mom=0.9)

In [5]:
def tst_param(val, grad=None):
    "Create a tensor with `val` and a gradient of `grad` for testing"
    set_trace()
    res = tensor([val]).float()
    res.grad = tensor([val/10 if grad is None else grad]).float()
    return res

In [8]:
p = tst_param([1,2,3], [4,5,6]) 

## Experiment average_grad with pdb

In [ ]:
state = {}
state = average_grad(p, mom=0.9, **state)

<function save_history at 0x148662d30>
> /var/folders/gz/ch3n2mp51m9386sytqf97s6w0000gn/T/ipykernel_43631/3504488234.py(5)average_grad()
      3     "Keeps track of the avg grads of `p` in `state` with `mom`."
      4     set_trace()
----> 5     if grad_avg is None: grad_avg = torch.zeros_like(p.grad.data)
      6     damp = 1-mom if dampening else 1.
      7     grad_avg.mul_(mom).add_(p.grad.data, alpha=damp)

ipdb> n
> /var/folders/gz/ch3n2mp51m9386sytqf97s6w0000gn/T/ipykernel_43631/3504488234.py(6)average_grad()
      4     set_trace()
      5     if grad_avg is None: grad_avg = torch.zeros_like(p.grad.data)
----> 6     damp = 1-mom if dampening else 1.
      7     grad_avg.mul_(mom).add_(p.grad.data, alpha=damp)
      8     return {'grad_avg': grad_avg}

ipdb> n
> /var/folders/gz/ch3n2mp51m9386sytqf97s6w0000gn/T/ipykernel_43631/3504488234.py(7)average_grad()
      5     if grad_avg is None: grad_avg = torch.zeros_like(p.grad.data)
      6     damp = 1-mom if dampening else 1.
----

In [ ]:
test_eq(state['grad_avg'], p.grad)
state = average_grad(p, mom=0.9, **state)
test_eq(state['grad_avg'], p.grad * 1.9)

<function save_history at 0x143faab80>
> /var/folders/gz/ch3n2mp51m9386sytqf97s6w0000gn/T/ipykernel_42776/3917144823.py(4)tst_param()
      2     "Create a tensor with `val` and a gradient of `grad` for testing"
      3     set_trace()
----> 4     res = tensor([val]).float()
      5     res.grad = tensor([val/10 if grad is None else grad]).float()
      6     return res

ipdb> a
val = [1, 2, 3]
grad = [4, 5, 6]
ipdb> [val]
[[1, 2, 3]]
ipdb> tensor([val])
tensor([[1, 2, 3]])
ipdb> tensor([val]).float()
tensor([[1., 2., 3.]])
ipdb> n
> /var/folders/gz/ch3n2mp51m9386sytqf97s6w0000gn/T/ipykernel_42776/3917144823.py(5)tst_param()
      2     "Create a tensor with `val` and a gradient of `grad` for testing"
      3     set_trace()
      4     res = tensor([val]).float()
----> 5     res.grad = tensor([val/10 if grad is None else grad]).float()
      6     return res

ipdb> [val/10 if grad is None else grad]
[[4, 5, 6]]
ipdb> tensor([val/10 if grad is None else grad])
tensor([[4, 5, 6]])
ipdb>

In [45]:
#Test dampening
state = {}
state = average_grad(p,  mom=0.9, dampening=True, **state)
test_eq(state['grad_avg'], 0.1*p.grad)
state = average_grad(p, mom=0.9, dampening=True, **state)
test_close(state['grad_avg'], (0.1*0.9+0.1)*p.grad)